import type { Metadata } from "next";
import '@mantine/core/styles.css';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createTheme, MantineProvider } from '@mantine/core';

const theme = createTheme({
  
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-br from-[#1e0848] via-[#1a1043] to-[#151136] text-white`}>
          <MantineProvider theme={theme}>
        {children}
        </MantineProvider>
      </body>
    </html>
  );
}
